spring:
  # profiles:
  #   active: single 
  application:
    name: api-interface
  # sessin失效时间1天 (min)
  session:   
    timeout: 86400
server:
  port: 8123
  # 统一将后端添加一个前缀/api (指定接口全局api)
  servlet:
    context-path: /api
springdoc:   # ip:port/api/doc.html  (/api/doc.html#/home)
  swagger-ui:
    # path配置swagger-ui.html  UI界面的访问路径，默认值
    path: /swagger-ui.html
    # tags-sorter接口文档中的tags排序规则，默认alpha（字母顺序）
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    # path配置api-docs的访问路径，默认 /v3/api-docs
    path: /v3/api-docs
  group-configs:
    # group-config配置分组信息
    - group: 'default'
      # group分组名称
      paths-to-match: '/**'
      # paths-to-match配置要匹配的路径，默认/**
      packages-to-scan: com.example.demo.controller
      # packages-to-scan配置要扫描的包的路径，直接配置为Controller类所在的包名即可
knife4j:
  enable: true 
  # true以启用Knife4j增强功能，将在应用程序中启用Knife4j UI
  setting:
    language: zh_cn
    # language设置Knife4j UI语言，可选zh_cn / en
  production: false 
  # 开启生产环境屏蔽
  basic:
    # 是否启用登录认证
    enable: false 
    username: admin  # 自定义
    password: 123456

api: 
  client:
    access-key: victory
    secret-key: victorysecretkey

